name: Go Build CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: "1.21"

    - name: Build
      run: |
        go mod tidy
        go build -o build/server ./server.go
        go build -o build/client ./client.go

    - name: Upload built binaries
      uses: actions/upload-artifact@v4
      with:
        name: go-binaries
        path: build/
